// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using OnCourse.Data;

namespace OnCourse.Migrations
{
    [DbContext(typeof(OnCourseContext))]
    partial class OnCourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnCourse.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 45,
                            Status = (byte)2,
                            Title = "C#: Primeiros Passos"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 15,
                            Status = (byte)2,
                            Title = "C#: Eventos, Delegates e Lambda"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 12,
                            Status = (byte)2,
                            Title = "Entity Framework Core: Banco de Dados de forma eficiente"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 25,
                            Status = (byte)2,
                            Title = "Microsserviços na prática: Entendendo a tomada de decisões"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 20,
                            Status = (byte)1,
                            Title = "Amazon Code Deploy: Deploy Continuo com AWS"
                        });
                });

            modelBuilder.Entity("OnCourse.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "dsteixeira",
                            Password = "pass1&",
                            Role = (byte)2
                        },
                        new
                        {
                            Id = 2,
                            Login = "rwsilva",
                            Password = "pass2&",
                            Role = (byte)3
                        },
                        new
                        {
                            Id = 3,
                            Login = "mcmorais",
                            Password = "pass3&",
                            Role = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
